### ISSUE TITLE
Choice Fields tends to use IntegerChoices - these are optimal, but make the datamodel a bit more difficult to use

### ISSUE THREAD

**Issue by kws** [SocialFinanceDigitalLabs/lw-ng#10]
Assuming there may be a general 'need' to run direct SQL analytics should anyone use this - shall we use text choices to make data slightly more human-friendly?

```
class ChecklistQuestionAnswer(models.IntegerChoices):
    NO = 0, _("No")
    YES = 1, _("Yes")
    NOT_RELEVANT = 2, _("This isn't relevant to me")


class NoteType(models.IntegerChoices):
    PA = 0, _("Pathway Plan PA")
    MANAGER = 1, _("Pathway Plan Manager")
```

**Comment by kws** [comment]
@cyramic do you have any views on this?

**Comment by cyramic** [comment]
Yes, I can see the logic behind that and think it would be a good way to go to make things easier to use.  I don't think we need to optimize everything considering the target audience. It's more about saving time. Happy to switch.
